name: CI

on:
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  build:
    name: Maven Build
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Cache Maven repository
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.sonar/cache
        key: ${{ runner.os }}-mvn-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-mvn-
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: zulu
    - name: Build with Maven
      run: |
        mvn verify \
        --batch-mode \
        --file portfolio-app/pom.xml

  build-analyze:
    name: Maven Build - ${{ matrix.os }}
    if: github.ref == 'refs/heads/master'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
      max-parallel: 4
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Cache Maven repository
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.sonar/cache
        key: ${{ runner.os }}-mvn-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-mvn-
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: zulu
        
    - name: Build with Maven
#      run: |
#        mvn verify sonar:sonar \
#        --batch-mode \
#        -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
#        --file portfolio-app/pom.xml
      run: |
        mvn verify --batch-mode --update-snapshots --file portfolio-app/pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
    - name: Create staging directory
      run: mkdir staging && cp **/target/*.jar staging && cp **/target/*.zip staging 
      
    - name: Copy artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
